
loaded({
   "request" : {
      "bedroom_max" : "100",
      "bedroom_min" : "0",
      "callback" : "loaded'",
      "country" : "uk",
      "language" : "en",
      "listing_type" : "buy",
      "location" : "hounslow",
      "num_res" : "15",
      "offset" : 0,
      "output" : "json_xs",
      "page" : "1",
      "pretty" : "1",
      "price_max" : "25000000",
      "price_min" : "0",
      "product_type" : "realestate",
      "property_type" : "property",
      "size_type" : "gross",
      "size_unit" : "m2",
      "sort" : "nestoria_rank",
      "updated_min" : "1341378000"
   },
   "response" : {
      "application_response_code" : "101",
      "application_response_text" : "best guess of ambiguous location",
      "attribution" : {
         "img_height" : 20,
         "img_url" : "http://static.nestoria.co.uk/i/realestate/uk/en/pb.png",
         "img_width" : 200,
         "link_to_img" : "http://www.nestoria.co.uk"
      },
      "created_http" : "Sat, 08 Jun 2013 13:30:46 GMT",
      "created_unix" : 1370698246,
      "link_to_url" : "http://www.nestoria.co.uk/hounslow/property/buy/maxprice-25000000/maxbed-100/results-15",
      "listings" : [
         {
            "auction_date" : null,
            "bathroom_number" : "1",
            "bedroom_number" : "1",
            "car_spaces" : null,
            "commission" : null,
            "construction_year" : null,
            "datasource_name" : "Moveto",
            "guid" : "g1-zNtkTNykTN0YwN==",
            "img_height" : 120,
            "img_url" : "http://1.l.uk.nestoria.nestimg.com/lis/6/3/9/1f94282316914fcdee7f3d68b5d7a614fa8b9.2.jpg",
            "img_width" : 160,
            "keywords" : "Loft, Reception",
            "latitude" : "51.47288",
            "lister_name" : "Rolfe East",
            "lister_url" : "http://rd.nestoria.co.uk/rd?l=WbeVkd5nm5odogZ5w&url=2-ePz73aTBU4LVGFByDI4-4Ner8aIMqOimmnO-vZos0aHemumced_H5rGuLADAKV0PxpsZtFi4Q-fUu6sPU8-oGzVguh9Phh3eelfSSVJrMef62ViqEdrSf0AlbLz8UGEghgfqpRYR1QyqMzxd9iD2fV94ogzZ78WAt7nNiLtwBn2VkyBpAjrOdXdvOQ4mZhuPTuyDXD_GEbPctyzaso0imGzxnJ7UNAlQcsjKI7lfs9TN0uuOPi9e4vKmu75qDEQPcufvsUeKBXs%3D&v=2&s=&itype=2",
            "listing_type" : "buy",
            "location_accuracy" : "9",
            "longitude" : "-0.38451",
            "price" : 179950,
            "price_coldrent" : 0,
            "price_currency" : "GBP",
            "price_formatted" : "179,950 GBP",
            "price_high" : 179950,
            "price_low" : 179950,
            "price_type" : "fixed",
            "property_type" : "flat",
            "summary" : "Conveniently located one double bedroom apartment. benefiting from a long...",
            "thumb_height" : 60,
            "thumb_url" : "http://3.l.uk.nestoria.nestimg.com/lis/6/3/9/1f94282316914fcdee7f3d68b5d7a614fa8b9.1.jpg",
            "thumb_width" : 60,
            "title" : "Cranston Close, Hounslow, TW3 - Loft",
            "updated_in_days" : 0.5,
            "updated_in_days_formatted" : "yesterday"
         },
         {
            "auction_date" : null,
            "bathroom_number" : "1",
            "bedroom_number" : "3",
            "car_spaces" : null,
            "commission" : null,
            "construction_year" : null,
            "datasource_name" : "Zoopla",
            "guid" : "g1-TNtcjM4AzNwQDN=Y",
            "img_height" : 120,
            "img_url" : "http://2.l.uk.nestoria.nestimg.com/lis/5/c/3/adb3a7e7dbf812fda8015f60742c5f4a1030c.2.jpg",
            "img_width" : 160,
            "keywords" : "Garden, Conversion, Detached, Loft, Parking",
            "latitude" : "51.44358",
            "lister_name" : "Silvertrees",
            "lister_url" : "http://rd.nestoria.co.uk/rd?l=UdeDSLnVUnWLWOHnf&url=2-ePz73aTBU4LVGFByDI484Ner8aIMqOimmnO-vZos3KDcnfaUecDe5LGyMAHFMUMLxpsZsli8WOfUu6sPU8-oGzVguh9PhB_YelfSSVJoMOr62ViqEdrSf0AlbLz8UGEghgfqpRYT0gCjNjxd9iD2fV94ogzZ78WAt7nPhrtwC32TlCFpAjjAcnpmMgsmZhuPTuyDXD_GEbPctyzaso0imGzmnIfBLAdQcsjKI7lfpcnQj_2dJiMU9bjn4-UzSV8Kbay56RLNETlri__v7BuLDF6aWrxDy0c9-HGuyYxm7G7AdHfrPEQjV0F2&v=2&s=&itype=2",
            "listing_type" : "buy",
            "location_accuracy" : "9",
            "longitude" : "-0.38677",
            "price" : 305000,
            "price_coldrent" : 0,
            "price_currency" : "GBP",
            "price_formatted" : "305,000 GBP",
            "price_high" : 305000,
            "price_low" : 305000,
            "price_type" : "fixed",
            "property_type" : "house",
            "summary" : "3 double bedroom semi detached family house in Hanworth. Featuring 1/2...",
            "thumb_height" : 60,
            "thumb_url" : "http://1.l.uk.nestoria.nestimg.com/lis/5/c/3/adb3a7e7dbf812fda8015f60742c5f4a1030c.1.jpg",
            "thumb_width" : 60,
            "title" : "Hounslow Road, Hanworth, Feltham, TW13",
            "updated_in_days" : 4.5,
            "updated_in_days_formatted" : "this week"
         },
         {
            "auction_date" : null,
            "bathroom_number" : "2",
            "bedroom_number" : "3",
            "car_spaces" : null,
            "commission" : null,
            "construction_year" : null,
            "datasource_name" : "Country Life",
            "guid" : "g1-TNtUTN0EjM2UwN==",
            "img_height" : 120,
            "img_url" : "http://3.l.uk.nestoria.nestimg.com/lis/7/f/3/229df414c2e749a0fa49a1c895a2759ffe19c.2.jpg",
            "img_width" : 160,
            "keywords" : "Garden, Garage, En suite, Reception",
            "latitude" : "51.47195",
            "lister_name" : "Hamptons",
            "lister_url" : "http://rd.nestoria.co.uk/rd?l=UdeDSLnVUnWLWOHng&url=2-ePz73aTBU4LVGFByDI484Ner8aIMqOimmnO-vZos3KDcnfaUecDe5LGyMAHFMUMLxpsZsli8WefUu6sPU8-oGzVguhhHgxDZelfSSVJrMub32ViqEdrSf0AlbLz8UGEghgfqpRYT1wWjNjxd9iD2fV94ogzZ78WAt7nPhLtwBnyflCFpAjrIdHpqOA8iZhuPTuyDXD_GEbPctyzaso0imGz_nJ3fNBQHfc6CM_wTrIjXyaGMOClL9K_n-6MqUV9IL_v-uFCNTmNt0KeBq0bLSArQFLNK3UA58A%3D%3D&v=2&s=&itype=2",
            "listing_type" : "buy",
            "location_accuracy" : "9",
            "longitude" : "-0.40186",
            "price" : 350000,
            "price_coldrent" : 0,
            "price_currency" : "GBP",
            "price_formatted" : "350,000 GBP",
            "price_high" : 350000,
            "price_low" : 350000,
            "price_type" : "fixed",
            "property_type" : "house",
            "summary" : "Brand new three-storey townhouse with three bedrooms, an ensuite to the...",
            "thumb_height" : 60,
            "thumb_url" : "http://2.l.uk.nestoria.nestimg.com/lis/7/f/3/229df414c2e749a0fa49a1c895a2759ffe19c.1.jpg",
            "thumb_width" : 60,
            "title" : "The Green, Beavers Lane, Hounslow, TW4",
            "updated_in_days" : 482.5,
            "updated_in_days_formatted" : "over a month ago"
         },
         {
            "auction_date" : null,
            "bathroom_number" : "9",
            "bedroom_number" : "9",
            "car_spaces" : null,
            "commission" : null,
            "construction_year" : null,
            "datasource_name" : "PrimeLocation",
            "guid" : "g1-jNtkjM4gTO4czM=I",
            "img_height" : 120,
            "img_url" : "http://3.l.uk.nestoria.nestimg.com/lis/d/e/a/bdecd3dee17ba79c741d470bea630830bd519.2.jpg",
            "img_width" : 160,
            "keywords" : "En suite",
            "latitude" : "51.48217",
            "lister_name" : "All bright Estates",
            "lister_url" : "http://rd.nestoria.co.uk/rd?l=VYeIXQsaZsbQbTMsm&url=2-ePz73aTBU4LVGFByDI424Ner8aIMqOimmnO-vZos3aDemuOdet_B5rCuKADHLkMOxp8Zsli8WefUu6sPU8-oGzVguhhHix7aelfSSVJkMe712ViqEdrSf0AlbLz8UGEghgfqpRYW1QCjNjxd9iD2fV94ogzZ78WAt7nMiLtzDHyTnSBpAjrNd3NrOgknZhuPTuyDXD_GEbPctyzaso0imGzsgYHcJQoRcsaQP70e7cXNz6GaJTQW4rz_56M7XwRZNPj98hDBHz8px6GCoAGKE2KMCKdU21Ym42Cw4sd2_GrqdC_pMFQqGQVuQLPaS4A%3D&v=2&s=&itype=2",
            "listing_type" : "buy",
            "location_accuracy" : "9",
            "longitude" : "-0.40965",
            "price" : 675000,
            "price_coldrent" : 0,
            "price_currency" : "GBP",
            "price_formatted" : "675,000 GBP",
            "price_high" : 675000,
            "price_low" : 675000,
            "price_type" : "fixed",
            "property_type" : "",
            "summary" : "Nine bedroom property ideal for large familly convenience or for investment...",
            "thumb_height" : 60,
            "thumb_url" : "http://2.l.uk.nestoria.nestimg.com/lis/d/e/a/bdecd3dee17ba79c741d470bea630830bd519.1.jpg",
            "thumb_width" : 60,
            "title" : "Avenue Gardens, Hounslow, TW5",
            "updated_in_days" : 122.5,
            "updated_in_days_formatted" : "over a month ago"
         },
         {
            "auction_date" : null,
            "bathroom_number" : "1",
            "bedroom_number" : "2",
            "car_spaces" : null,
            "commission" : null,
            "construction_year" : null,
            "datasource_name" : "whathouse",
            "guid" : "g1-zMtgjN5gTO=U",
            "img_height" : 120,
            "img_url" : "http://3.l.uk.nestoria.nestimg.com/lis/5/5/c/578d34cb21397df15b4c3b922ef94f3d206b5.2.jpg",
            "img_width" : 160,
            "keywords" : "Freehold, Dishwasher, Central Heating",
            "latitude" : "51.46706",
            "lister_name" : "New on What House?",
            "lister_url" : "http://rd.nestoria.co.uk/rd?l=WWeQfY0ih0jYjbU0v&url=2-ePz73aTBU4LVGFByDI494Ner8aIMqOimmnO-vZos3KDcnfaUecDe5LGyMATFNEMOxp8Zsli8WOfUu6sPU8-oGzVguh9OgRDWelfSSVJqNO_02ViqEdrSf0AlbLz8UGEghgfqpRYS1gWjNjxd9iD2fV94ogzZ78WAt7nJibtzDXeXlCFpAjjAdXBsOAkpZhuPTuyDXD_GEbPctyzaso0imGzrm4nFKAkLYsLKNb1ets2N0vyTOiNJ5bT28aMqVBlMOPCjtU2MVGMzkffHskbTHFibFb1J1R4qoHa3-ZNm8SrUaSv_LUwiShcmTbjcB47GyiYTncxdxm6FfzAUbUbC8oU5mvqk1vkJUTdY2T1xnP1JxHrwZQWi&v=2&s=&itype=2",
            "listing_type" : "buy",
            "location_accuracy" : "9",
            "longitude" : "-0.39389",
            "price" : 240000,
            "price_coldrent" : 0,
            "price_currency" : "GBP",
            "price_formatted" : "240,000 GBP",
            "price_high" : 240000,
            "price_low" : 240000,
            "price_type" : "fixed",
            "property_type" : "",
            "summary" : "SpecificationGeneral 150 year leases to apartments, freehold houses 10-year...",
            "thumb_height" : 60,
            "thumb_url" : "http://2.l.uk.nestoria.nestimg.com/lis/5/5/c/578d34cb21397df15b4c3b922ef94f3d206b5.1.jpg",
            "thumb_width" : 60,
            "title" : "New Bedroom 1 Storey Apartment In Hounslow, TW4",
            "updated_in_days" : 1014.5,
            "updated_in_days_formatted" : "over a month ago"
         },
         {
            "auction_date" : null,
            "bathroom_number" : "1",
            "bedroom_number" : "1",
            "car_spaces" : null,
            "commission" : null,
            "construction_year" : null,
            "datasource_name" : "needaproperty.com",
            "guid" : "g1-DOtYDN1EDM2YQO==",
            "img_height" : 120,
            "img_url" : "http://1.l.uk.nestoria.nestimg.com/lis/f/3/1/43baa3904962e95b803cfdce206708f97ca48.2.jpg",
            "img_width" : 160,
            "keywords" : "Dishwasher, Parking, Patio, Reception",
            "latitude" : "51.46113",
            "lister_name" : "Rolfe East",
            "lister_url" : "http://rd.nestoria.co.uk/rd?l=VXeHWPrZYraPaSLrn&url=2-ePz73aTBU4LVGFByDI4-4Ner8aIMqOimmnO-vZos3KDcnfaUecDe5LGyMATFNEMOxp8Zsli8WefUu6sPU8-oGzVguh9PhhrZelfSSVJqMu7x2ViqEdrSf0AlbLz8UGEghgfqpRYS0gyqMzxd9iD2fV94ogzZ78WAt7nCh7tzCnaWkiFpAjrNc3ptPQoiZhuPTuyDXD_GEbPctyzaso0imGzylo3VIRYMfteBJKYJ7cXNz6GMOClL9K_n-6M5VQIVLvXiuA2xSHNwjP7f6FmqKQnKJYoJiR5Z6GGx-Y5upUHZeD6gbRByFFU9HPXU&v=2&s=&itype=2",
            "listing_type" : "buy",
            "location_accuracy" : "9",
            "longitude" : "-0.38426",
            "price" : 209950,
            "price_coldrent" : 0,
            "price_currency" : "GBP",
            "price_formatted" : "209,950 GBP",
            "price_high" : 209950,
            "price_low" : 209950,
            "price_type" : "fixed",
            "property_type" : "flat",
            "summary" : "One double bedroom apartment. benefiting from a great sized bedroom and...",
            "thumb_height" : 60,
            "thumb_url" : "http://3.l.uk.nestoria.nestimg.com/lis/f/3/1/43baa3904962e95b803cfdce206708f97ca48.1.jpg",
            "thumb_width" : 60,
            "title" : "Flat, Helix Ct Hedera Pl, Hounslow, TW4",
            "updated_in_days" : 60.5,
            "updated_in_days_formatted" : "over a month ago"
         },
         {
            "auction_date" : null,
            "bathroom_number" : "",
            "bedroom_number" : "2",
            "car_spaces" : null,
            "commission" : null,
            "construction_year" : null,
            "datasource_name" : "SmartNewHomes",
            "guid" : "g1-zMtkjdtEndSNlSFZWZx80VqpWa4sVQ1dXdWpwZ==",
            "img_height" : 120,
            "img_url" : "http://1.l.uk.nestoria.nestimg.com/lis/c/0/4/7a0f5367cc776968d55661b3910965c1ccfa4.2.jpg",
            "img_width" : 160,
            "keywords" : "New Build",
            "latitude" : "51.47020",
            "lister_name" : "United House",
            "lister_url" : "http://rd.nestoria.co.uk/rd?l=VaeKZSucbudSdVOur&url=2-ePz73aTBU4LVGFByDI494Ner8aIMqO2gnnO9u5wrxKjdhfaeeMPe4rGzMAHFMUMMxpsZsli8WefUu6sPU8-oGzVguhhHgBDfelfSSVJrM-3y2ViqEdrSf0AlbLz8TnY-ugC99lhEwA-iKi4B4mXSWi1g_RLJrJaSvbecndEDb2faiDM3UCvCZ3FnJw8jdAeZDLPeTzLWS_6f9SHXsdggnS6-ycrZNBIOK4jLIaUH7dXPw_yIJCNM-bL-5_9xWR9VcvfhsE-WSSlylvzbsRWNDkXADp5P1lhSyTiN85J353XceHD9K043Hg1jA7aUW8mZk2YJyIFO&v=2&s=&itype=2",
            "listing_type" : "buy",
            "location_accuracy" : "9",
            "longitude" : "-0.40280",
            "price" : 220000,
            "price_coldrent" : 0,
            "price_currency" : "GBP",
            "price_formatted" : "220,000 GBP",
            "price_high" : 220000,
            "price_low" : 220000,
            "price_type" : "fixed",
            "property_type" : "flat",
            "summary" : "",
            "thumb_height" : 60,
            "thumb_url" : "http://3.l.uk.nestoria.nestimg.com/lis/c/0/4/7a0f5367cc776968d55661b3910965c1ccfa4.1.jpg",
            "thumb_width" : 60,
            "title" : "The Green, Hounslow, TW4 - New Build",
            "updated_in_days" : 1062.5,
            "updated_in_days_formatted" : "over a month ago"
         },
         {
            "auction_date" : null,
            "bathroom_number" : "1",
            "bedroom_number" : "2",
            "car_spaces" : null,
            "commission" : null,
            "construction_year" : null,
            "datasource_name" : "Zoopla",
            "guid" : "g1-TNtcjMykTNxkTO=A",
            "img_height" : 120,
            "img_url" : "http://3.l.uk.nestoria.nestimg.com/lis/a/3/a/8b13f3fc74709d6c85b61a0e94eba6394f010.2.jpg",
            "img_width" : 160,
            "keywords" : "Leasehold, Balcony, Porter, Purpose Built, Patio, Dishwasher, En suite, Reception",
            "latitude" : "51.47111",
            "lister_name" : "Fraser",
            "lister_url" : "http://rd.nestoria.co.uk/rd?l=WYeSha2kj2laldW20&url=2-ePz73aTBU4LVGFByDI494Ner8aIMqOimmnO-vZos3KDcnfaUecDe5LGyMATFNEMOxp8Zsli8WefUu6sPU8-oGzVguh9BgBnfelfSSVJrMu7z2ViqEdrSf0AlbLz8UGEghgfqpRYS0QyqMzxd9iD2fV94ogzZ78WAt7nPhrt5CnOfkzx1AD_IdHZmOwQzaBXYSfLNRCeMDbPY_Tna6o0iwTjznJjdIUgdfomRPf0WrNSP0e-QL2lf9Kny6-AsFUIBb6G37BvJGHNqks3D8AGMHVjCCbdVzBVu-Wic-4Rn4XLYJCzoPEU0Bh4%3D&v=2&s=&itype=2",
            "listing_type" : "buy",
            "location_accuracy" : "9",
            "longitude" : "-0.36210",
            "price" : 239950,
            "price_coldrent" : 0,
            "price_currency" : "GBP",
            "price_formatted" : "239,950 GBP",
            "price_high" : 239950,
            "price_low" : 239950,
            "price_type" : "fixed",
            "property_type" : "flat",
            "summary" : "Sixth floor purpose built flat situated in the modern residential...",
            "thumb_height" : 60,
            "thumb_url" : "http://2.l.uk.nestoria.nestimg.com/lis/a/3/a/8b13f3fc74709d6c85b61a0e94eba6394f010.1.jpg",
            "thumb_width" : 60,
            "title" : "Blenheim Centre, Prince Regent Rd, Hounslow, TW3",
            "updated_in_days" : 4.5,
            "updated_in_days_formatted" : "this week"
         },
         {
            "auction_date" : null,
            "bathroom_number" : "1",
            "bedroom_number" : "3",
            "car_spaces" : null,
            "commission" : null,
            "construction_year" : null,
            "datasource_name" : "Zoopla",
            "guid" : "g1-TNtcjM0ATMzMTM=U",
            "img_height" : 120,
            "img_url" : "http://2.l.uk.nestoria.nestimg.com/lis/1/c/b/00d2b8e5da6a24ec678e21ab683fc2af455c3.2.jpg",
            "img_width" : 160,
            "keywords" : "Ex Local Auth",
            "latitude" : "51.46986",
            "lister_name" : "Citywest",
            "lister_url" : "http://rd.nestoria.co.uk/rd?l=VXeHWPrZYraPaSLrq&url=2-ePz73aTBU4LVGFByDI484Ner8aIMqOimmnO-vZos3KDcnfaUecDe5LGyMATFNEMOxp8Zsli8WOfUu6sPU8-oGzVguhhHgRvbelfSSVJqOuf02ViqEdrSf0AlbLz8UGEghgfqpRYS0QGqMzxd9iD2fV94ogzZ78WAt7nPhrtzDXSQliNpAjjAcHZpOgkmZhuPTuyDXD_GEbPctyzaso0imGzmnIfBLAdQcsjKI7lfpcnQj_2dJiMU9bjn4-UzSV8KbaC_7hHIEjlri__v7BuLDF6aWrxDy0c9-HGuyYxm7G7AdHfrPEQjV0F2&v=2&s=&itype=2",
            "listing_type" : "buy",
            "location_accuracy" : "9",
            "longitude" : "-0.40334",
            "price" : 234950,
            "price_coldrent" : 0,
            "price_currency" : "GBP",
            "price_formatted" : "234,950 GBP",
            "price_high" : 234950,
            "price_low" : 234950,
            "price_type" : "fixed",
            "property_type" : "house",
            "summary" : "Ex-Local Authority, Three double bedroom flat, first floor. Large bedrooms...",
            "thumb_height" : 60,
            "thumb_url" : "http://1.l.uk.nestoria.nestimg.com/lis/1/c/b/00d2b8e5da6a24ec678e21ab683fc2af455c3.1.jpg",
            "thumb_width" : 60,
            "title" : "Chester Road, Hounslow W., Hounslow, TW4",
            "updated_in_days" : 990.5,
            "updated_in_days_formatted" : "over a month ago"
         },
         {
            "auction_date" : null,
            "bathroom_number" : "1",
            "bedroom_number" : "3",
            "car_spaces" : null,
            "commission" : null,
            "construction_year" : null,
            "datasource_name" : "Zoopla",
            "guid" : "g1-TNtcjM2gDN0QDN=I",
            "img_height" : 120,
            "img_url" : "http://1.l.uk.nestoria.nestimg.com/lis/4/d/8/20a00370c02ebcebd8212f23d2ae07a23f99b.2.jpg",
            "img_width" : 160,
            "keywords" : "Garden",
            "latitude" : "51.46860",
            "lister_name" : "iHomes",
            "lister_url" : "http://rd.nestoria.co.uk/rd?l=WWeQfY0ih0jYjbU0rq&url=2-ePz73aTBU4LVGFByDI484Ner8aIMqOimmnO-vZos3KDcnfaUecDe5LGyMATFNEMOxp8Zsli8WOfUu6sPU8-oGzVguh9OihHfelfSSVJqO-ny2ViqEdrSf0AlbLz8UGEghgfqpRYS0wyqMzxd9iD2fV94ogzZ78WAt7nPhrtwB3CRkCBpAjrMcXpqOA0pZhuPTuyDXD_GEbPctyzaso0imGzmnIfBLAdQcsjKI7lfpcnQj_2dJiMU9bjn4-UzSV8KZaK66RbNFTlri__v7BuLDF6aWrxDy0c9-HGuyYxm7G7AdHfrPEQjV0F2&v=2&s=&itype=2",
            "listing_type" : "buy",
            "location_accuracy" : "9",
            "longitude" : "-0.39890",
            "price" : 219950,
            "price_coldrent" : 0,
            "price_currency" : "GBP",
            "price_formatted" : "219,950 GBP",
            "price_high" : 219950,
            "price_low" : 219950,
            "price_type" : "fixed",
            "property_type" : "house",
            "summary" : "Lounge: 14'1 x 11'6 bedroom 1: 13'9 x 7'6 bedroom 2: 13'11 x 11 bedroom 3:...",
            "thumb_height" : 60,
            "thumb_url" : "http://3.l.uk.nestoria.nestimg.com/lis/4/d/8/20a00370c02ebcebd8212f23d2ae07a23f99b.1.jpg",
            "thumb_width" : 60,
            "title" : "Rectory Road, Hounslow, TW4 - Garden",
            "updated_in_days" : 208.5,
            "updated_in_days_formatted" : "over a month ago"
         },
         {
            "auction_date" : null,
            "bathroom_number" : "1",
            "bedroom_number" : "4",
            "car_spaces" : null,
            "commission" : null,
            "construction_year" : null,
            "datasource_name" : "Zoopla",
            "guid" : "g1-TNtcjM4gjNzAzN=k",
            "img_height" : 120,
            "img_url" : "http://1.l.uk.nestoria.nestimg.com/lis/e/3/9/38dd4d84c71ab49c4bfcdbf3c0a52943921b1.2.jpg",
            "img_width" : 160,
            "keywords" : "Garden, Off Street Parking, Conservatory, Reception, Central Heating",
            "latitude" : "51.47570",
            "lister_name" : "DBK",
            "lister_url" : "http://rd.nestoria.co.uk/rd?l=UYe-NGiQPiRGRJCiZZ&url=2-ePz73aTBU4LVGFByDI474Ner8aIMqOimmnO-vZos3KDcnfaUecDe5LGyMAHFMUMLxpsZsli8WefUu6sPU8-oGzVguhhHghHdelfSSVJrNujy2ViqEdrSf0AlbLz8UGEghgfqpRYS2gGqMzxd9iD2fV94ogzZ78WAt7nPhrtwCnSQlCJpAjrNdHJrOgQjZhuPTuyDXD_GEbPctyzaso0imGzmnIfBLAdQcsjKI7lfpcnQj_2dJiMU9bjn4-UzSV8KZay47RHOHjlri__v7BuLDF6aWrxDy0c9-HGuyYxm7G7AdHfrPEQjV0F2&v=2&s=&itype=2",
            "listing_type" : "buy",
            "location_accuracy" : "9",
            "longitude" : "-0.40092",
            "price" : 284950,
            "price_coldrent" : 0,
            "price_currency" : "GBP",
            "price_formatted" : "284,950 GBP",
            "price_high" : 284950,
            "price_low" : 284950,
            "price_type" : "fixed",
            "property_type" : "house",
            "summary" : "Semi detached house moments from Hounslow West Station. Kept to a high...",
            "thumb_height" : 60,
            "thumb_url" : "http://3.l.uk.nestoria.nestimg.com/lis/e/3/9/38dd4d84c71ab49c4bfcdbf3c0a52943921b1.1.jpg",
            "thumb_width" : 60,
            "title" : "Cedar Road, Hounslow, TW4 - Reception",
            "updated_in_days" : 140.5,
            "updated_in_days_formatted" : "over a month ago"
         },
         {
            "auction_date" : null,
            "bathroom_number" : "2",
            "bedroom_number" : "3",
            "car_spaces" : null,
            "commission" : null,
            "construction_year" : null,
            "datasource_name" : "Zoopla",
            "guid" : "g1-TNtcjMygDN3cjN=A",
            "img_height" : 120,
            "img_url" : "http://1.l.uk.nestoria.nestimg.com/lis/8/3/8/7c8223c5cf756af34bc9d6cccc881a5b9fa94.2.jpg",
            "img_width" : 160,
            "keywords" : "Garden, Purpose Built, Loft, Off Street Parking, Reception",
            "latitude" : "51.47546",
            "lister_name" : "MFS",
            "lister_url" : "http://rd.nestoria.co.uk/rd?l=UbeBQJlTSlUJUMFlcd&url=2-ePz73aTBU4LVGFByDI484Ner8aIMqOimmnO-vZos3KDcnfaUecDe5LGyMAHFMUMLxpsZsli8WOfUu6sPU8-oGzVguhhHghncelfSSVJrNuv02ViqEdrSf0AlbLz8UGEghgfqpRYT1QGqMzxd9iD2fV94ogzZ78WAt7nPhrtwDHOSnSdpAjrKdnVnOA8nZhuPTuyDXD_GEbPctyzaso0imGzmnIfBLAdQcsjKI7lfpcnQj_2dJiMU9bjn4-UzSV8KZaa66hXPFzlri__v7BuLDF6aWrxDy0c9-HGuyYxm7G7AdHfrPEQjV0F2&v=2&s=&itype=2",
            "listing_type" : "buy",
            "location_accuracy" : "9",
            "longitude" : "-0.40013",
            "price" : 374950,
            "price_coldrent" : 0,
            "price_currency" : "GBP",
            "price_formatted" : "374,950 GBP",
            "price_high" : 374950,
            "price_low" : 374950,
            "price_type" : "fixed",
            "property_type" : "house",
            "summary" : "Hazlemere rd, hounslow, middlesex, tw5 9ut the accommodation with...",
            "thumb_height" : 60,
            "thumb_url" : "http://3.l.uk.nestoria.nestimg.com/lis/8/3/8/7c8223c5cf756af34bc9d6cccc881a5b9fa94.1.jpg",
            "thumb_width" : 60,
            "title" : "Hazelmere Road, Hounslow, TW5 - Loft",
            "updated_in_days" : 344.5,
            "updated_in_days_formatted" : "over a month ago"
         },
         {
            "auction_date" : null,
            "bathroom_number" : "1",
            "bedroom_number" : "3",
            "car_spaces" : null,
            "commission" : null,
            "construction_year" : null,
            "datasource_name" : "Zoopla",
            "guid" : "g1-TNtcTM4gTNyMDM=A",
            "img_height" : 120,
            "img_url" : "http://1.l.uk.nestoria.nestimg.com/lis/8/b/3/c53d76e1d58387f4182ef280c9a0d3bca711a.2.jpg",
            "img_width" : 160,
            "keywords" : "Garden, Patio, Central Heating",
            "latitude" : "51.47235",
            "lister_name" : "Bridge",
            "lister_url" : "http://rd.nestoria.co.uk/rd?l=VVeFUNpXWpYNYQJpgi&url=2-ePz73aTBU4LVGFByDI484Ner8aIMqOimmnO-vZos3KDcnfaUecDe5LGyMATFNEMOxp8Zsli8WefUu6sPU8-oGzVguh9OhRzaelfSSVJrMez32ViqEdrSf0AlbLz8UGEghgfqpRYR2gWjNjxd9iD2fV94ogzZ78WAt7nPhrt4D3SXkjx1Aj7LcXppOQszaBXYSfLNRCeMDbPY_Tna6o0iwTjznJjdIUgdfomRPf0WrNSP0e-QL2lf9Kny6-AsFUEAZaG97xLJGHNqks3D8AGMHVjCCbdVzBVu-Wic-4Rn4XLYJCzoPEU0Bh4%3D&v=2&s=&itype=2",
            "listing_type" : "buy",
            "location_accuracy" : "9",
            "longitude" : "-0.39745",
            "price" : 180000,
            "price_coldrent" : 0,
            "price_currency" : "GBP",
            "price_formatted" : "180,000 GBP",
            "price_high" : 180000,
            "price_low" : 180000,
            "price_type" : "fixed",
            "property_type" : "house",
            "summary" : "Concrete built property- cash buyers or investors only bridge property...",
            "thumb_height" : 60,
            "thumb_url" : "http://3.l.uk.nestoria.nestimg.com/lis/8/b/3/c53d76e1d58387f4182ef280c9a0d3bca711a.1.jpg",
            "thumb_width" : 60,
            "title" : "Ermine Close, Hounslow, Middlesex, TW4",
            "updated_in_days" : 1058.5,
            "updated_in_days_formatted" : "over a month ago"
         },
         {
            "auction_date" : null,
            "bathroom_number" : "1",
            "bedroom_number" : "1",
            "car_spaces" : null,
            "commission" : null,
            "construction_year" : null,
            "datasource_name" : "Zoopla",
            "guid" : "g1-TNtcjM4YTN3cTM=E",
            "img_height" : 120,
            "img_url" : "http://1.l.uk.nestoria.nestimg.com/lis/f/4/c/e704164ae00f5d39910b3b3ca80a53333666d.2.jpg",
            "img_width" : 160,
            "keywords" : "Loft, Reception",
            "latitude" : "51.48200",
            "lister_name" : "haart",
            "lister_url" : "http://rd.nestoria.co.uk/rd?l=VdeNcVxfexgVgYRxor&url=2-ePz73aTBU4LVGFByDI4-4Ner8aIMqOimmnO-vZos3KDcnfaUecDe5LGyMATFNEMOxp8Zsli8WefUu6sPU8-oGzVguhhHih7belfSSVJkMe_y2ViqEdrSf0AlbLz8UGEghgfqpRYR1AKjNjxd9iD2fV94ogzZ78WAt7nPhrtzCXWekSlpAjvIcnVqMwklZhuPTuyDXD_GEbPctyzaso0imGzmnIfBLAdQcsjKI7lfpcnQj_2dJiMU9bjn4-UzSV8Ka6y76hXIFjlri__v7BuLDF6aWrxDy0c9-HGuyYxm7G7AdHfrPEQjV0F2&v=2&s=&itype=2",
            "listing_type" : "buy",
            "location_accuracy" : "9",
            "longitude" : "-0.40864",
            "price" : 167000,
            "price_coldrent" : 0,
            "price_currency" : "GBP",
            "price_formatted" : "167,000 GBP",
            "price_high" : 167000,
            "price_low" : 167000,
            "price_type" : "fixed",
            "property_type" : "house",
            "summary" : "Porch Side aspect frosted door, side aspect window and door to reception...",
            "thumb_height" : 60,
            "thumb_url" : "http://3.l.uk.nestoria.nestimg.com/lis/f/4/c/e704164ae00f5d39910b3b3ca80a53333666d.1.jpg",
            "thumb_width" : 60,
            "title" : "Hawthorn Close, Hounslow, TW5 - Loft",
            "updated_in_days" : 808.5,
            "updated_in_days_formatted" : "over a month ago"
         },
         {
            "auction_date" : null,
            "bathroom_number" : "1",
            "bedroom_number" : "3",
            "car_spaces" : null,
            "commission" : null,
            "construction_year" : null,
            "datasource_name" : "Zoopla",
            "guid" : "g1-TNtcjM0czNycjN=k",
            "img_height" : 120,
            "img_url" : "http://1.l.uk.nestoria.nestimg.com/lis/7/e/2/0b327d82096a083b6a5f71e0534799023aaff.2.jpg",
            "img_width" : 160,
            "keywords" : "Leasehold",
            "latitude" : "51.45350",
            "lister_name" : "Landmarks",
            "lister_url" : "http://rd.nestoria.co.uk/rd?l=UaeAPIkSRkTITLEkbf&url=2-ePz73aTBU4LVGFByDI484Ner8aIMqOimmnO-vZos3KDcnfaUecDe5LGyMATFNEMOxp8Zsli8WOfUu6sPU8-oGzVguhhEghjZelfSSVJpMOry2ViqEdrSf0AlbLz8UGEghgfqpRYR1QCjNjxd9iD2fV94ogzZ78WAt7nPhrtwDn2VkCBpAjvAd3JqOggpZhuPTuyDXD_GEbPctyzaso0imGzmnIfBLAdQcsjKI7lfpcnQj_2dJiMU9bjn4-UzSV8KaqC56hDPHjlri__v7BuLDF6aWrxDy0c9-HGuyYxm7G7AdHfrPEQjV0F2&v=2&s=&itype=2",
            "listing_type" : "buy",
            "location_accuracy" : "9",
            "longitude" : "-0.43006",
            "price" : 175000,
            "price_coldrent" : 0,
            "price_currency" : "GBP",
            "price_formatted" : "175,000 GBP",
            "price_high" : 175000,
            "price_low" : 175000,
            "price_type" : "fixed",
            "property_type" : "flat",
            "summary" : "Staines road, bedfont entrance hallway stairs to first floor landing lounge...",
            "thumb_height" : 60,
            "thumb_url" : "http://3.l.uk.nestoria.nestimg.com/lis/7/e/2/0b327d82096a083b6a5f71e0534799023aaff.1.jpg",
            "thumb_width" : 60,
            "title" : "Staines Road, Hounslow, TW14",
            "updated_in_days" : 600.5,
            "updated_in_days_formatted" : "over a month ago"
         }
      ],
      "locations" : [
         {
            "center_lat" : "51.469774",
            "center_long" : "-0.419406",
            "long_title" : "Hounslow",
            "place_name" : "hounslow",
            "title" : "Hounslow"
         },
         {
            "center_lat" : "51.462522",
            "center_long" : "-0.361803",
            "long_title" : "Hounslow Railway Station",
            "place_name" : "hounslow-railway-station",
            "title" : "Hounslow Railway Station"
         }
      ],
      "page" : "1",
      "sort" : "nestoria_rank",
      "status_code" : "200",
      "status_text" : "OK",
      "thanks" : "For using the Nestoria API.",
      "total_pages" : 49,
      "total_results" : 732
   }
}
)